apiVersion: v1
kind: Service
metadata:
  name: aether
  namespace: aether
  labels:
    app: aether
spec:
  type: LoadBalancer
  selector:
    app: aether
  ports:
    - name: http
      port: 3000
      targetPort: http
